<?php /** @var $block \Bogkov\Contact\Block\Adminhtml\Contact\View */ ?>
<div class="contact">
    <div class="contact-info">
        <div><span><?php echo __('Name') ?>: </span><?php /* @escapeNotVerified */ echo $block->getContact()->getData('user_name') ?></div>
        <div><span><?php echo __('Email') ?>: </span><?php /* @escapeNotVerified */ echo $block->getContact()->getData('user_email') ?></div>
        <div><span><?php echo __('Phone Number') ?>: </span><?php /* @escapeNotVerified */ echo $block->getContact()->getData('phone_number') ?></div>
    </div>
    <?php /** @var $message \Bogkov\Contact\Model\ContactMessage */ ?>
    <?php foreach ($block->getContactMessages() as $message): ?>
        <div class="item contact-message <?php /* @escapeNotVerified */ echo $message->getData('type_code') ?>">
            <div class="contact-message-head">
                <?php if (\Bogkov\Contact\Model\ResourceModel\ContactMessage::TYPE_CODE_CUSTOMER === $message->getData('type_code')) : ?>
                    <?php /* @escapeNotVerified */ echo __('Customer wrote at %1:', $block->formatDateTime($message->getData('created_at'), 'M j, Y H:i:s A')) ?>
                <?php else : ?>
                    <?php /* @escapeNotVerified */ echo __('Administrator answered at %1:', $block->formatDateTime($message->getData('created_at'), 'M j, Y H:i:s A')) ?>
                <?php endif ?>
            </div>
            <div>
                <?php /* @escapeNotVerified */ echo $message->getData('text') ?>
            </div>
        </div>
    <?php endforeach ?>
    <div style="clear: both"></div>
</div>
